name: build-macos-universal

on:
  push:
    branches: [ main, master ]
    paths: [ 'exciter8~.c', '.github/workflows/build-macos-universal.yml' ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Pure Data header
        run: |
          curl -L https://raw.githubusercontent.com/pure-data/pure-data/master/src/m_pd.h -o m_pd.h

      - name: Compile Universal macOS .pd_darwin
        run: |
          clang -O3 -std=c99 -DPD -I. \
            -arch x86_64 -arch arm64 \
            -mmacosx-version-min=10.13 \
            -bundle -undefined dynamic_lookup \
            exciter8~.c -o exciter8~.pd_darwin

      - name: Show file info
        run: |
          file exciter8~.pd_darwin
          otool -hv exciter8~.pd_darwin || true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exciter8_macos_universal
          path: exciter8~.pd_darwin
